//! Codegen backend trait — §25.2.

use rava_common::error::Result;
use rava_rir::Module;
use std::path::Path;

/// Emits native code from an optimized RIR module.
///
/// Default implementation: `CraneliftBackend` (in `rava-codegen-cranelift`).
/// Optional: `LlvmBackend` (feature flag — slower compile, better codegen quality).
pub trait CodegenBackend: Send + Sync {
    fn name(&self) -> &'static str;

    /// Emit a complete native binary from the module to `output`.
    fn emit(&self, module: &Module, output: &Path) -> Result<()>;
}

/// GC stack map — records which stack slots/registers hold references at each safepoint.
/// Generated by the codegen backend and embedded in the binary (§27.2).
#[derive(Debug, Clone)]
pub struct GcMap {
    /// Instruction offset from function start (in bytes).
    pub pc_offset: u32,
    /// Bitmap of stack slots that contain object references (1 bit = 1 slot).
    pub stack_ref_bitmap: u64,
    /// Bitmap of registers that contain object references.
    pub reg_ref_bitmap: u32,
}

/// Relocation entry — a symbol reference in the emitted machine code that needs linking.
#[derive(Debug, Clone)]
pub struct Reloc {
    /// Byte offset within the emitted code where the relocation applies.
    pub offset: u32,
    /// Name of the symbol being referenced.
    pub symbol: String,
}
